name: Mirror to GitLab
on:
  push:
    branches: ["main"]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:glpat-tYoMz9DcRwC4dxBWpLaym286MQp1OjFibW5hCw.01.1208hgh82@gitlab.com/personal-kind/earthquake-ph-nodejs.git
          git push --mirror gitlab